### ISSUE TITLE
core.pager override doesn't work well with `git log`

### ISSUE THREAD

**Issue by ymichael** [banga/git-split-diffs#1]
I gave this a go and it works great for `git show` & `git diff`! But the core.pager override  breaks git log for me.. it doesn't page anymore

**Comment by banga** [comment]
Can you share more details? It works for me with `git log -p` (or regular git log, which doesn't include diffs).

**Comment by banga** [comment]
To be clear, git-split-diffs doesn't implement paging, you need to pipe it through `less`. I do `git config --global core.pager git-split-diffs --color | less -RFX`

**Comment by ymichael** [comment]
OH I need to do 
```
 git config --global --replace-all core.pager 'git-split-diffs --color | less -RFX'
```

**Comment by ymichael** [comment]
I see this:

```
➜  git config --global core.pager git-split-diffs --color | less -RFX
➜  git config --global --get core.pager
git-split-diffs
➜  git config --global --replace-all core.pager 'git-split-diffs --color | less -RFX'
➜  git config --global --get core.pager
git-split-diffs --color | less -RFX

**Comment by ymichael** [comment]
Sorry I didn't think to do `--get` to debug this before making this issue!

**Comment by banga** [comment]
Ah no worries!
