### ISSUE TITLE
How do I get it to do side-by-side?

### ISSUE THREAD

**Issue by gigatexal** [banga/git-split-diffs#12]
I followed the instructions from the README:

```
npm install -g git-split-diffs

git config --global core.pager "git-split-diffs --color | less -RFX"
```

But I don't see side-by-side diffs.

git version:

`git version 2.31.1`

os version:

`Darwin 19.6.0 Darwin Kernel Version 19.6.0: Tue Jan 12 22:13:05 PST 2021; root:xnu-6153.141.16~1/RELEASE_X86_64 x86_64
`

**Comment by banga** [comment]
The default behavior is that on narrow windows, we revert back to unified diffs because split diffs are hard to read if your window is too narrow: https://github.com/banga/git-split-diffs#narrow-terminals. If you want, you can disable this:
```
git config split-diffs.min-line-width 0
```

**Comment by gigatexal** [comment]
Thanks a lot!
