### ISSUE TITLE
Other similar project

### ISSUE THREAD

**Issue by bew** [banga/git-split-diffs#14]
Hello,
I'm a user of another similar tool named delta: https://github.com/dandavison/delta

I just discovered your project, and as I didn't see it in the acknowledged tools, I was wondering if you knew about it (:
Maybe you can take inspiration from delta too if you want some of its featuresin this project!

**Comment by banga** [comment]
Thanks, yes I heard about it recently after I was nearly done implementing this. It's definitely very impressive and more feature rich. It looks like they implement a complete pager, which would be a lot more work, but will keep an eye out for features that I can support here easily
