### ISSUE TITLE
ExperimentalWarning message being displayed

### ISSUE THREAD

**Issue by jaypuk** [banga/git-split-diffs#20]
Hi
I'm getting the following warning displayed whenever I run git-split-diff
`(node:364) ExperimentalWarning: Conditional exports is an experimental feature. This feature could change at any time`

Functionally though all seems fine.

fyi I'm on MacOs with node v13.7.0, and I'm running the app via iTerm2 using `git diff | git-split-diffs --color`
(Unfortunately I'm not a node developer so can't help in trying to fix this.)

**Comment by banga** [comment]
Yeah I can repro this on `v13.7.0`. This warning seems to be coming from some dependency but it's hard to track down which one. So I see two options for you to get rid of these:
- Update to `v13.10.0`, which removes these warnings (https://nodejs.org/en/blog/release/v13.10.0/, https://github.com/nodejs/node/pull/31845)
- Disable all node warnings by setting the `NODE_NO_WARNINGS` environment variable
Hope that helps
