### ISSUE TITLE
windows terminal display is not normal

### ISSUE THREAD

**Issue by yefengwu** [banga/git-split-diffs#22]
## When I use less, the display will appear as follows.
![image](https://user-images.githubusercontent.com/45461486/127966590-8ece4bb6-58aa-4aa6-aaa6-ab64cebff8ca.png)

**Comment by banga** [comment]
If possible, can you either share that file or a link to the repo and commit where this happens?

**Comment by tkarndt** [comment]
same for me. Any news?
Happens in PowerShell in all themes
