### ISSUE TITLE
SLOW

### ISSUE THREAD

**Issue by zuanzuanshao** [banga/git-split-diffs#24]
The speed is too slow, disable syntax highlighting is also slow. Are there other ways to speed things up?

**Comment by banga** [comment]
That's a bit surprising if it's still slow after disabling syntax highlighting. Which terminal app do you use? Some terminals handle colors and fonts much better. If you're using iTerm in particular, one perf issue I had was when I had "Use ligatures" checked in the font settings that made text rendering much slower.
