### ISSUE TITLE
Less sometimes stop working, key will print in cmd line diretly.

### ISSUE THREAD

**Issue by gitsang** [banga/git-split-diffs#27]
Less sometimes stop working, key will print in cmd line diretly without doing anything. I have no idea if it is cause by git-split-diffs. I have never meet that case before.

![image](https://user-images.githubusercontent.com/49085035/129345955-4c6c0fb7-0574-4488-a79a-ab811b9689a8.png)

Often happens when press `j` continuously.

![image](https://user-images.githubusercontent.com/49085035/129346495-d31c9e7a-ba15-433d-b5e5-cca49e423371.png)

And can not quit less by pressing `q` or `ctrl + c` or `^]`. The only way I found to quit is `ctrl + z`.

```
# less --version
less 458 (POSIX regular expressions)
Copyright (C) 1984-2012 Mark Nudelman

less comes with NO WARRANTY, to the extent permitted by law.
For information about the terms of redistribution,
see the file named README in the less distribution.
Homepage: http://www.greenwoodsoftware.com/less
```

**Comment by banga** [comment]
Oof this happens to me too and annoyingly doesn’t reproduce on the same input twice. Are you able to repro it consistently?

**Comment by gitsang** [comment]
Can't, it is difficult to reproduce the same situation.

**Comment by banga** [comment]
Merging this into #16, which I believe is the same issue
