### ISSUE TITLE
[Feature Request] Support diff two local files directly not in git repository

### ISSUE THREAD

**Issue by fengzilong** [banga/git-split-diffs#29]
```bash
git-split-diffs oldfile newfile
```

If would be convenient if git-split-diffs could support this

**Comment by banga** [comment]
you can do this [using git](https://stackoverflow.com/questions/11561498/how-to-compare-two-files-not-in-repo-using-git):
```
git diff --no-index file1.txt file2.txt
```
so if you have git-split-diffs set up to work with git, this will show you a nicer diff

**Comment by fengzilong** [comment]
Thanks, nice tips
