### ISSUE TITLE
Is it possible to use a different differ under the hood?

### ISSUE THREAD

**Issue by mimoo** [banga/git-split-diffs#36]
Hey! I'm using git-split-diffs all the time, but I'd like if it could use this https://github.com/wilfred/difftastic under the hood. Are these tools composable?

**Comment by banga** [comment]
If difftastic can be made to output in the patch format that git uses, then yes it would be pretty easy to hook it up. But I didn't see an option to that from a quick look. It seems like difftastic combines the diffing algo with its own formatting? cc @wilfred if you have any suggestions.

**Comment by banga** [comment]
Ah from the readme:

> Patching. Difftastic output is intended for human consumption, and it does not generate patches that you can apply later. Use diff if you need a patch.

So probably not

**Comment by mimoo** [comment]
ah dang :( can't have the best of both world, thanks though!

**Comment by jmmendivil** [comment]
Is this still not possible, even with the `--display inline` option?
