### ISSUE TITLE
Diffs are not split but linear

### ISSUE THREAD

**Issue by Anunayj** [banga/git-split-diffs#4]
What I'm getting:
![image](https://user-images.githubusercontent.com/26520192/116794636-19fdcf80-aaec-11eb-8094-48843042e3a9.png)
```
$ git config --global --get core.pager
git-split-diffs --color | less -RFX
```

What I expected:
![image](https://user-images.githubusercontent.com/26520192/116794686-942e5400-aaec-11eb-9817-747fb136b8fb.png)
Old Content on left side and new on right side.

**Comment by banga** [comment]
See https://github.com/banga/git-split-diffs#narrow-terminals. We revert to unified diffs if your terminal is too narrow. You can prevent this by setting `min-line-width` to 0.
