### ISSUE TITLE
File name disappears in git version 2.38.1

### ISSUE THREAD

**Issue by CatChen** [banga/git-split-diffs#41]
Broken version: git version 2.38.1
Working version: git version 2.37.1 (Apple Git-137.1)

`git diff` output is slightly different between these two versions. In the working version, it's like this:

```
diff --git a/modified.txt b/modified.txt
index 1dd297ad..1cb605b6 100644
--- a/modified.txt
+++ b/modified.txt
```

In the broken version, it's like this:

```
diff --git modified.txt modified.txt
index 12ea6ab..c801668 100644
--- modified.txt
+++ modified.txt
```

The `a/` and `b/` are gone. `git-split-diffs` fails to parse the file name when `a/` and `b/` are gone and thus displaying every file without a file name. Otherwise, everything else still works.

**Comment by banga** [comment]
I just updated to git 2.39.0 and still don't see this behavior. I see your fix, but unfortunately it breaks a test case (file deletion). Can you share more detailed repro steps and any special config settings you might have (check `git config -l`)?
