### ISSUE TITLE
No syntax highlighting in git-split-diffs@0.13.0

### ISSUE THREAD

**Issue by lantw44** [banga/git-split-diffs#43]
After updating to the latest version, I can no longer reliably see syntax highlighting. I could reproduce the issue by running `git show 07e85b10b850630332aba1e4d85aa099911fe3df src/iterSideBySideDiffs.ts | git-split-diffs` in this repository.

git-split-diffs@0.10.0
![螢幕快照 2023-01-16 10-24-01](https://user-images.githubusercontent.com/3016644/212585571-cb8eca67-0973-4972-91ff-d264dbdbb4c4.png)

git-split-diffs@0.13.0
![螢幕快照 2023-01-16 10-24-38](https://user-images.githubusercontent.com/3016644/212585595-5835df2b-3dbd-4bd2-9447-0657487ad424.png)

**Comment by mtsknn** [comment]
I too have syntax highlighting problems with versions 0.11.0, 0.12.0 and 0.13.0. Version 0.10.0 works well.

**Comment by banga** [comment]
Apologies. https://github.com/banga/git-split-diffs/commit/e7319d1e3ea7234482892402a3836d4417a3b3da should fix it, which I've published in v0.14.0. Can you all try it out?

**Comment by lantw44** [comment]
0.14.0 seems to fix the problem for me.

**Comment by mtsknn** [comment]
0.14.0 seems to so far work for me too. 👍 Thanks for the fix!

**Comment by banga** [comment]
Thanks for reporting!
