### ISSUE TITLE
diff not opened in separate view & mouse scrolling not working with git v2.41.0.windows.2 in standard git bash console

### ISSUE THREAD

**Issue by Velociraptor45** [banga/git-split-diffs#45]
After upgrading git to v2.41.0.windows.2, the diff does not open in a separate view in the standard git bash console anymore that you can quit with 'q' and scrolling with the mouse wheel doesn't also work anymore (only with the arrow keys). I came from v.2.39.0.windows.2.

Interestingly, in the normal windows cmd, the separate view is opened, however, the scrolling also doesn't work (but I can't tell if that worked before)

I checked the active git config and my setting `core.pager=git-split-diffs --color | less -+LFX` is still there, so scrolling should still be activated.

It looks like this now when I execute a git diff:
![grafik](https://github.com/banga/git-split-diffs/assets/30436688/33d36a9d-e90c-491d-a12e-287f5eeb20ee)

**Comment by banga** [comment]
I think unfortunately this is likely to be an issue with `less`, not `git-split-diffs`. Essentially, `git-split-diffs` just spits out the entire colorized diff and `less` (which is shipped with your OS) handles the scrolling and navigation. I suspect that the terminal emulator you're using (is it git bash?) behaves differently from linux. https://unix.stackexchange.com/questions/469360/less-performs-differently-when-invoked-from-bash-and-from-git is one example complaining about this. You can try changing the arguments passed to it in git config and seeing if that takes effect. Btw, you seem to have `less -+RFX`, whereas I use `less -RFX`, not sure if that makes a difference.

**Comment by Velociraptor45** [comment]
Thanks for looking into it. The issue seems to have been fixed with git v2.42.0 :)

Regarding the `less -+RFX`: Your documentation in the README says to use the `+` in order to enable scrolling (altought I just noticed the documentation describes `-+LFX`, but I assume the `L` is not the significant part there?)
