### ISSUE TITLE
unified diffs display

### ISSUE THREAD

**Issue by qxxiao** [banga/git-split-diffs#50]
When using unified diffs for display two files, some lines of differences might be missing compared to the original git diff, while the side by side display works normally( and `git diff -- file1` is ok). Why is this happening?

eg.  
original:  
<img width="498" alt="image" src="https://github.com/banga/git-split-diffs/assets/43007848/0b9e0052-70ed-4bad-b601-db7500344c05">

unified diffs:  
<img width="540" alt="image" src="https://github.com/banga/git-split-diffs/assets/43007848/88bf367a-1aa6-4c69-8ad4-6ecae8295018">

side by side:  
<img width="883" alt="image" src="https://github.com/banga/git-split-diffs/assets/43007848/657ade47-49b2-48e2-9a37-fcfc96c6ba06">

**Comment by banga** [comment]
Thanks for the report! I deployed [version 1.2.0](https://www.npmjs.com/package/git-split-diffs/v/1.2.0) with the fix for this issue. Try updating to it and let me know if you still run into any issues.
