### ISSUE TITLE
need to mark 2.0.0 github release

### ISSUE THREAD

**Issue by chenrui333** [banga/git-split-diffs#52]
👋 looks like the github release did not get completed, raised this issue for some awareness. Thanks!

relates to https://github.com/Homebrew/homebrew-core/pull/176033

**Comment by banga** [comment]
Ah thanks, didn’t realize this tool had made it to homebrew. I published it without setting it to latest because I wanted to test it first. Is anything breaking imminently on homebrew side or can it wait a few more days?

**Comment by chenrui333** [comment]
@banga thanks for pushing to a new release, but it would be also good to mark 2.0.1 release as latest release :) 

<img width="1573" alt="image" src="https://github.com/banga/git-split-diffs/assets/1580956/87388635-a368-467b-8843-94b2ff632db6">

anyway, [we have shipped 2.0.1](https://github.com/Homebrew/homebrew-core/pull/176393) on the homebrew side, 💯
